export enum ItemEnum {
    DESTINY_GUARDIAN_STONE = "Destiny Guardian Stone",
    DESTINY_DESTRUCTION_STONE = "Destiny Destruction Stone",
    DESTINY_LEAPSTONE = "Destiny Leapstone",
    DESTINY_SHARD = "Destiny Shard",
    DESTINY_SHARD_POUCH_S = "Destiny Shard Pouch S",
    DESTINY_SHARD_POUCH_M = "Destiny Shard Pouch M",
    DESTINY_SHARD_POUCH_L = "Destiny Shard Pouch L",
    GLACIERS_BREATH = "Glacier's Breath",
    LAVAS_BREATH = "Lava's Breath",
    ABIDOS_FUSION_MATERIAL = "Abidos Fusion Material",
    SPECIAL_HONING_CIRCULATED_LEAPSTONE = "Special Honing: Circulated Leapstone",
    METALLURGY_HELLFIRE_11_14 = "Metallurgy: Hellfire[11-14]",
    TAILORING_HELLFIRE_11_14 = "Tailoring: Hellfire[11-14]",

    REFINED_PROTECTION_STONE = "Refined Protection Stone",
    REFINED_OBLITERATION_STONE = "Refined Obliteration Stone",
    RADIANT_HONOR_LEAPSTONE = "Radiant Honor Leapstone",
    HONOR_SHARD = "HONOR Shard",
    HONOR_SHARD_POUCH_S = "Honor Shard Pouch S",
    HONOR_SHARD_POUCH_M = "Honor Shard Pouch M",
    HONOR_SHARD_POUCH_L = "Honor Shard Pouch L",
    PRIME_OREHA_FUSION_MATERIAL = "Prime Oreha Fusion Material",
    SPECIAL_HONING_CONCENTRATED_LEAPSTONE = "Special Honing: Concentrated Leapstone",
    METALLURGY_DECAY_13_15 = "Metallurgy: Decay[13-15]",
    TAILORING_DECAY_13_15 = "Tailoring: Decay[13-15]",
    METALLURGY_DECAY_16_19 = "Metallurgy: Decay[16-19]",
    TAILORING_DECAY_16_19 = "Tailoring: Decay[16-19]",

    PROTECTION_STONE = "Protection Stone",
    OBLITERATION_STONE = "Obliteration Stone",
    MARVELOUS_HONOR_LEAPSTONE = "Marvelous Honor Leapstone",
    SUPERIOR_OREHA_FUSION_MATERIAL = "Superior Oreha Fusion Material",

    SOLAR_GRACE = "Solar Grace",
    SOLAR_BLESSING = "Solar Blessing",
    SOLAR_PROTECTION = "Solar Protection",

    SUNSET_SCALE = "Sunset Scale",
    ARGOS_BLOOD = "Argos Blood",
    DEMON_BEAST_BONE = "Demon Beast Bone",
    COVETOUS_WING = "Covetous Wing",
    MAYHEM_HORN = "Mayhem Horn",
    PHANTOM_INTENTION = "Phantom Intention",
    LIGHTS_TRIAL = "Light's Trial",
    EMPYREAN_CONTEMPLATION = "Empyrean Contemplation",
    EYE_OF_DECAY = "Eye of Decay",
    SPLENDID_ENERGY_OF_WISDOM = "Clear Energy of Wisdom",
    SPLENDID_ELIXIR_OF_WISDOM = "Clear Elixir of Wisdom",
    DARK_FIRE = "Dark Fire",
    MAGICAL_SPRING_WATER = "Magical Spring Water",
    AGRIS_SCALE = "Agris Scale",
    ALCAONE_EYE = "Alcaone Eye",
    BEHEMOTH_SCALE = "Behemoth Scale",
    HELLFIRE_KEYSTONE = "Hellfire Keystone",

    TRANSCENDENCE_TICKET_WEAPON = "Transcendence Ticket Weapon",
    TRANSCENDENCE_TICKET_ARMOR = "Transcendence Ticket Armor",
    CLEAR_MEDAL = "Clear Medal",
    SYLMAEL_BLOODSTONE = "Sylmael Bloodstone",

    EXPERT_TOKEN = "Expert Token",
    SOLO_TOKEN = "Solo Token",
    BLUE_CRYSTAL = "Blue Crystal",
    GOLD = "Gold",

    ABILITY_STONE = "Ability Stone",
    RELIC_ENGRAVING = "Relic Engraving",
    LEGENDARY_ENGRAVING = "Legendary Engraving",
    GOLD_BAR_BOUND = "Gold Bar(Bound)",
}